name: Java CI with Gradle

on:
  push:
    branches: [ "master", $default-branch ]
  pull_request:
    branches: [ "master", $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

#   https://github.com/marketplace/actions/setup-java-jdk
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build